//! Reader + writer functions for the `ip_hostname_cache` hypertable.
//!
//! Runtime `sqlx::query` / `query_as` is used here (not the `query!` macros)
//! because these queries target a table that is not yet in the committed
//! `.sqlx/` offline cache. The cache is regenerated by a later task.
//!
//! All functions take any `sqlx::Executor<'_, Database = Postgres>`, so
//! callers can pass `&pool`, `&mut conn`, or `&mut *tx` interchangeably.
//! This lets integration tests wrap DML in a transaction and roll back,
//! matching the shared-pool isolation contract documented in
//! `tests/common/mod.rs`.
use std::collections::HashMap;
use std::net::IpAddr;

use sqlx::Postgres;

use crate::hostname::canonicalize;

/// Look up the most-recent non-expired hostname for each requested IP.
///
/// Returned map semantics — keys mirror the **caller's input shape**
/// (not the DB's canonical form), so `map.get(&requested_ip)` works
/// regardless of whether the caller passed an IPv4-mapped IPv6 address
/// or a plain IPv4 address. If the caller passes multiple inputs that
/// canonicalize to the same DB row, every input appears in the returned
/// map pointing at the same value.
///
/// - `Some(Some(hostname))` — positive hit.
/// - `Some(None)` — negative hit (confirmed NXDOMAIN in cache).
/// - key absent — cold cache: caller should enqueue a lookup.
pub async fn hostnames_for<'c, E>(
    executor: E,
    ips: &[IpAddr],
) -> sqlx::Result<HashMap<IpAddr, Option<String>>>
where
    E: sqlx::Executor<'c, Database = Postgres>,
{
    if ips.is_empty() {
        return Ok(HashMap::new());
    }

    let canonical: Vec<IpAddr> = ips.iter().copied().map(canonicalize).collect();

    let rows: Vec<(IpAddr, Option<String>)> = sqlx::query_as::<Postgres, (IpAddr, Option<String>)>(
        r#"
            SELECT DISTINCT ON (ip) ip, hostname
            FROM ip_hostname_cache
            WHERE ip = ANY($1)
              AND resolved_at > NOW() - INTERVAL '90 days'
            ORDER BY ip, resolved_at DESC
            "#,
    )
    .bind(&canonical)
    .fetch_all(executor)
    .await?;

    let by_canonical: HashMap<IpAddr, Option<String>> = rows.into_iter().collect();
    Ok(ips
        .iter()
        .filter_map(|ip| {
            by_canonical
                .get(&canonicalize(*ip))
                .cloned()
                .map(|value| (*ip, value))
        })
        .collect())
}

/// Insert a positive hit: `(ip, hostname)`.
pub async fn record_positive<'c, E>(executor: E, ip: IpAddr, hostname: &str) -> sqlx::Result<()>
where
    E: sqlx::Executor<'c, Database = Postgres>,
{
    let canonical = canonicalize(ip);
    sqlx::query("INSERT INTO ip_hostname_cache (ip, hostname) VALUES ($1, $2)")
        .bind(canonical)
        .bind(hostname)
        .execute(executor)
        .await?;
    Ok(())
}

/// Insert a negative hit: `(ip, NULL)` — confirmed NXDOMAIN.
pub async fn record_negative<'c, E>(executor: E, ip: IpAddr) -> sqlx::Result<()>
where
    E: sqlx::Executor<'c, Database = Postgres>,
{
    let canonical = canonicalize(ip);
    sqlx::query("INSERT INTO ip_hostname_cache (ip, hostname) VALUES ($1, NULL)")
        .bind(canonical)
        .execute(executor)
        .await?;
    Ok(())
}
