//! Reader + writer functions for the `ip_hostname_cache` hypertable.
//!
//! Runtime `sqlx::query` / `query_as` is used here (not the `query!` macros)
//! because these queries target a table that is not yet in the committed
//! `.sqlx/` offline cache. The cache is regenerated by a later task.
use std::collections::HashMap;
use std::net::IpAddr;

use sqlx::{PgPool, Postgres};

use crate::hostname::canonicalize;

/// Look up the most-recent non-expired hostname for each requested IP.
///
/// Returned map semantics:
/// - `Some(Some(hostname))` — positive hit.
/// - `Some(None)` — negative hit (confirmed NXDOMAIN in cache).
/// - key absent — cold cache: caller should enqueue a lookup.
pub async fn hostnames_for(
    pool: &PgPool,
    ips: &[IpAddr],
) -> sqlx::Result<HashMap<IpAddr, Option<String>>> {
    if ips.is_empty() {
        return Ok(HashMap::new());
    }

    let canonical: Vec<IpAddr> = ips.iter().copied().map(canonicalize).collect();

    let rows: Vec<(IpAddr, Option<String>)> = sqlx::query_as::<Postgres, (IpAddr, Option<String>)>(
        r#"
            SELECT DISTINCT ON (ip) ip, hostname
            FROM ip_hostname_cache
            WHERE ip = ANY($1)
              AND resolved_at > NOW() - INTERVAL '90 days'
            ORDER BY ip, resolved_at DESC
            "#,
    )
    .bind(&canonical)
    .fetch_all(pool)
    .await?;

    Ok(rows.into_iter().collect())
}

/// Insert a positive hit: `(ip, hostname)`.
pub async fn record_positive(pool: &PgPool, ip: IpAddr, hostname: &str) -> sqlx::Result<()> {
    let canonical = canonicalize(ip);
    sqlx::query("INSERT INTO ip_hostname_cache (ip, hostname) VALUES ($1, $2)")
        .bind(canonical)
        .bind(hostname)
        .execute(pool)
        .await?;
    Ok(())
}

/// Insert a negative hit: `(ip, NULL)` — confirmed NXDOMAIN.
pub async fn record_negative(pool: &PgPool, ip: IpAddr) -> sqlx::Result<()> {
    let canonical = canonicalize(ip);
    sqlx::query("INSERT INTO ip_hostname_cache (ip, hostname) VALUES ($1, NULL)")
        .bind(canonical)
        .execute(pool)
        .await?;
    Ok(())
}
