/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/agents` — return every agent known to the registry.
         * @description The response is a flat JSON array sorted by `id` for determinism.
         *     Empty when no agents have registered yet.
         */
        get: operations["list_agents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/agents/{id}` — return a single agent by id.
         * @description Returns 404 with a JSON error body when the id is not found in the
         *     current registry snapshot.
         */
        get: operations["get_agent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/alerts` — proxy active alerts from Alertmanager.
         * @description Returns a normalized `Vec<AlertSummary>`. Upstream query parameters
         *     (`active`, `silenced`, `inhibited`, `unprocessed`, `filter`) are
         *     forwarded verbatim.
         *
         *     - **503** when `upstream.alertmanager_url` is not configured.
         *     - **502** when the upstream is unreachable or returns a non-2xx status.
         */
        get: operations["list_alerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{fingerprint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/alerts/{fingerprint}` — single alert by fingerprint.
         * @description Fetches the full alert list from Alertmanager and filters client-side
         *     by fingerprint (the v2 API has no single-alert endpoint).
         *
         *     - **404** when no alert matches the fingerprint.
         *     - **502** when the upstream is unreachable or returns a non-2xx status.
         *     - **503** when `upstream.alertmanager_url` is not configured.
         */
        get: operations["get_alert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST `/api/auth/login` — authenticate and issue a session cookie.
         * @description - 200 + `LoginResponse` on success
         *     - 401 on wrong credentials (JSON body: `{"error": "invalid credentials"}`)
         *     - 500 only on infra failure (session store I/O, verify-task panic)
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST `/api/auth/logout` — invalidate the current session.
         * @description Idempotent: 200 whether or not the caller was logged in. The cookie is
         *     cleared either way.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/metrics/query` -- proxy an instant query to VictoriaMetrics.
         * @description The query expression must reference at least one `meshmon_<ident>`
         *     metric. Aggregators and function wrappers around meshmon metrics are
         *     allowed. Queries that touch no meshmon metric are rejected with 400.
         *
         *     - **400** when the query references no `meshmon_` metric.
         *     - **502** when the upstream is unreachable or returns an error.
         *     - **503** when `upstream.vm_url` is not configured.
         */
        get: operations["query_instant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/query_range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/metrics/query_range` -- proxy a range query to VictoriaMetrics.
         * @description The query expression must reference at least one `meshmon_<ident>`
         *     metric. Aggregators and function wrappers around meshmon metrics are
         *     allowed. Queries that touch no meshmon metric are rejected with 400.
         *
         *     - **400** when the query references no `meshmon_` metric.
         *     - **502** when the upstream is unreachable or returns an error.
         *     - **503** when `upstream.vm_url` is not configured.
         */
        get: operations["query_range"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paths/{src}/{tgt}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/paths/{src}/{tgt}/overview` — aggregate path-detail payload. */
        get: operations["path_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paths/{src}/{tgt}/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/paths/{src}/{tgt}/routes` — return a paginated, time-filtered
         *     list of route snapshot summaries (without hop detail).
         */
        get: operations["list_routes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paths/{src}/{tgt}/routes/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/paths/{src}/{tgt}/routes/latest` — return the most recent
         *     route snapshot for the given source, target, and protocol.
         */
        get: operations["get_route_latest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paths/{src}/{tgt}/routes/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/paths/{src}/{tgt}/routes/{snapshot_id}` — return a single
         *     route snapshot by database id.
         */
        get: operations["get_route_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/routes/recent` — returns the latest route snapshot per
         *     `(source_id, target_id)` pair, newest first, up to `limit` rows
         *     (default 10, max 100).
         */
        get: operations["list_recent_routes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/web-config` — return the frontend runtime config.
         * @description This handler is registered behind the `login_required!` layer, so
         *     unauthenticated requests never reach it — they are short-circuited by
         *     the middleware with a plain 401. The 401 response is documented here so
         *     the generated OpenAPI schema tells SPA clients exactly what to expect.
         */
        get: operations["web_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Summary of a single agent, returned by the list and detail endpoints.
         *
         *     Write-only on the server (constructed and serialized, never parsed) so
         *     only `Serialize` is derived.
         */
        AgentSummary: {
            /** @description Optional agent version string. */
            agent_version?: string | null;
            /** @description Human-readable display label. */
            display_name: string;
            /** @description Unique agent identifier (matches the agent's `AGENT_ID` env var). */
            id: string;
            /** @description Agent source IP (host address only, CIDR prefix stripped). */
            ip: string;
            /**
             * Format: date-time
             * @description Last successful push (register/metrics/snapshot).
             */
            last_seen_at: string;
            /**
             * Format: double
             * @description Optional latitude.
             */
            lat?: number | null;
            /** @description Optional free-form location string. */
            location?: string | null;
            /**
             * Format: double
             * @description Optional longitude.
             */
            lon?: number | null;
            /**
             * Format: date-time
             * @description When this agent first registered.
             */
            registered_at: string;
        };
        /**
         * @description Normalized alert summary exposed by the meshmon API.
         *
         *     Derived from the Alertmanager v2 alert model, keeping only the fields
         *     the frontend needs. `generatorURL` and other upstream-only fields are
         *     intentionally dropped.
         */
        AlertSummary: {
            /** @description Longer description from the `description` annotation. */
            description?: string | null;
            /**
             * @description RFC 3339 timestamp when the alert resolved (may be empty/zero for
             *     active alerts).
             */
            ends_at: string;
            /** @description Alertmanager fingerprint (hex string), unique per alert group. */
            fingerprint: string;
            /** @description Label set attached to the alert (alertname, severity, etc.). */
            labels: {
                [key: string]: string;
            };
            /** @description RFC 3339 timestamp when the alert started firing. */
            starts_at: string;
            /** @description Alert state: `active`, `suppressed`, or `unprocessed`. */
            state: string;
            /** @description Short human-readable summary from the `summary` annotation. */
            summary?: string | null;
        };
        /** @description JSON representation of an observed IP at a hop. */
        HopIpJson: {
            /**
             * Format: double
             * @description Fraction of probes that observed this IP at this hop.
             */
            freq: number;
            /** @description Human-readable IP string (IPv4 or IPv6 `to_string()` form). */
            ip: string;
        };
        /**
         * @description JSON representation of a single traceroute hop as stored in
         *     `route_snapshots.hops`.
         */
        HopJson: {
            /**
             * Format: int32
             * @description Mean RTT to this hop, in microseconds.
             */
            avg_rtt_micros: number;
            /**
             * Format: double
             * @description Fraction of probes with no response at this hop.
             */
            loss_pct: number;
            /** @description IP addresses observed at this hop and their frequencies. */
            observed_ips: components["schemas"]["HopIpJson"][];
            /**
             * Format: int32
             * @description 1-indexed TTL / hop position (matches the protocol contract).
             */
            position: number;
            /**
             * Format: int32
             * @description Standard deviation of RTT to this hop, in microseconds.
             */
            stddev_rtt_micros: number;
        };
        /** @description Query parameters for `GET /api/metrics/query` (instant query). */
        InstantQuery: {
            /** @description PromQL expression. Must reference at least one `meshmon_` metric. */
            query: string;
            /** @description Optional evaluation timestamp (RFC 3339 or Unix epoch). */
            time?: string | null;
        };
        /**
         * @description Per-protocol latest-snapshot map. Each field is independent so the UI can
         *     render "icmp present, udp/tcp empty" without a sentinel value.
         */
        LatestByProtocol: {
            icmp?: null | components["schemas"]["RouteSnapshotDetail"];
            tcp?: null | components["schemas"]["RouteSnapshotDetail"];
            udp?: null | components["schemas"]["RouteSnapshotDetail"];
        };
        /** @description POST body for `/api/auth/login`. */
        LoginRequest: {
            /**
             * @description Plaintext password. Verified against the PHC hash via argon2 inside
             *     `spawn_blocking`.
             */
            password: string;
            /** @description Username from the configured `[auth.users]` list. */
            username: string;
        };
        /** @description JSON response body for `/api/auth/login`. */
        LoginResponse: {
            /** @description Echoed username on success. */
            username: string;
        };
        /** @description VictoriaMetrics-sourced RTT / loss series for the primary protocol. */
        PathMetrics: {
            /**
             * Format: double
             * @description Last loss value (fraction), or null if the series is empty.
             */
            loss_current?: number | null;
            /** @description `[epoch_ms, loss_fraction]` tuples. Fractional — `0.05` = 5%. */
            loss_series: number[][];
            /**
             * Format: double
             * @description Last RTT value (ms), or null if the series is empty.
             */
            rtt_current?: number | null;
            /** @description `[epoch_ms, rtt_ms]` tuples. */
            rtt_series: number[][];
        };
        /** @description Aggregated response for the Path Detail page. */
        PathOverviewResponse: {
            /** @description Latest snapshot per protocol within the window (each field optional). */
            latest_by_protocol: components["schemas"]["LatestByProtocol"];
            metrics?: null | components["schemas"]["PathMetrics"];
            /**
             * @description Server-picked primary protocol (`icmp`, `udp`, or `tcp`). `null`
             *     only when no protocol has any snapshot in the window; callers should
             *     treat that as "show a neutral empty state".
             */
            primary_protocol?: string | null;
            /**
             * @description Recent snapshots in the window in descending `observed_at` order,
             *     filtered to the resolved [`PathOverviewResponse::primary_protocol`].
             *     Capped at [`RECENT_LIMIT`]; no hop detail. `null`/empty when no
             *     primary protocol could be resolved (no data for any protocol in
             *     the window).
             */
            recent_snapshots: components["schemas"]["RouteSnapshotSummary"][];
            /**
             * @description `true` when the per-primary-protocol `recent_snapshots` list was
             *     clamped at [`RECENT_LIMIT`]. Since the list is protocol-scoped
             *     from the start, this flag is always honest for the operator-visible
             *     banner ("narrow the window for more").
             */
            recent_snapshots_truncated: boolean;
            /** @description Source agent metadata. */
            source: components["schemas"]["AgentSummary"];
            /** @description Server-chosen Prometheus step (`1m`, `5m`, `1h`, `6h`). */
            step: string;
            /** @description Target agent metadata. */
            target: components["schemas"]["AgentSummary"];
            /** @description Echoed resolved window bounds (inclusive). */
            window: components["schemas"]["WindowBounds"];
        };
        /**
         * @description JSON representation of the aggregated path summary stored in
         *     `route_snapshots.path_summary`.
         */
        PathSummaryJson: {
            /**
             * Format: int32
             * @description Mean RTT across all hops, in microseconds.
             */
            avg_rtt_micros: number;
            /**
             * Format: int32
             * @description Total number of hops in the route.
             */
            hop_count: number;
            /**
             * Format: double
             * @description Overall path loss fraction.
             */
            loss_pct: number;
        };
        /** @description Query parameters for `GET /api/metrics/query_range` (range query). */
        RangeQuery: {
            /** @description End timestamp (RFC 3339 or Unix epoch). */
            end: string;
            /** @description PromQL expression. Must reference at least one `meshmon_` metric. */
            query: string;
            /** @description Start timestamp (RFC 3339 or Unix epoch). */
            start: string;
            /** @description Query resolution step (e.g. `15s`, `1m`). */
            step: string;
        };
        /** @description Full detail of a single route snapshot (includes hops). */
        RouteSnapshotDetail: {
            /** @description Hop-by-hop detail. */
            hops: components["schemas"]["HopJson"][];
            /**
             * Format: int64
             * @description Database row id.
             */
            id: number;
            /**
             * Format: date-time
             * @description When the snapshot was observed.
             */
            observed_at: string;
            path_summary?: null | components["schemas"]["PathSummaryJson"];
            /** @description Protocol used for the traceroute (icmp, tcp, udp). */
            protocol: string;
            /** @description Source agent identifier. */
            source_id: string;
            /** @description Target agent identifier. */
            target_id: string;
        };
        /** @description Summary of a route snapshot (no hops — used in list responses). */
        RouteSnapshotSummary: {
            /**
             * Format: int64
             * @description Database row id.
             */
            id: number;
            /**
             * Format: date-time
             * @description When the snapshot was observed.
             */
            observed_at: string;
            path_summary?: null | components["schemas"]["PathSummaryJson"];
            /** @description Protocol used for the traceroute (icmp, tcp, udp). */
            protocol: string;
            /** @description Source agent identifier. */
            source_id: string;
            /** @description Target agent identifier. */
            target_id: string;
        };
        /** @description Paginated response of route snapshot summaries. */
        RoutesPage: {
            /** @description Snapshot summaries in descending `observed_at` order. */
            items: components["schemas"]["RouteSnapshotSummary"][];
            /**
             * Format: int64
             * @description Applied limit.
             */
            limit: number;
            /**
             * Format: int64
             * @description Current offset.
             */
            offset: number;
        };
        /**
         * @description Runtime config the frontend needs before it can render dashboards.
         *
         *     Returned from `GET /api/web-config`; doubles as the SPA's session probe
         *     (401 when the caller has no valid session cookie).
         *
         *     Write-only on the server — we only ever construct and serialize this
         *     type, never parse one back in — so only `Serialize` is derived.
         *     Matches the pattern used by [`crate::http::auth::LoginResponse`].
         */
        WebConfigResponse: {
            /**
             * @description Alertmanager base URL for constructing "view in Alertmanager"
             *     deep links (e.g., `https://alertmanager.example/`). `None` when
             *     Alertmanager is not configured — omitted from the JSON body.
             */
            alertmanager_base_url?: string | null;
            /**
             * @description Base URL for embedding Grafana panels (e.g., `https://grafana.example/`).
             *     `None` if Grafana is not configured — omitted from the JSON body.
             */
            grafana_base_url?: string | null;
            /**
             * @description Map of logical dashboard name → Grafana dashboard UID. Empty
             *     when Grafana integration is not configured.
             */
            grafana_dashboards: {
                [key: string]: string;
            };
            /**
             * @description Signed-in username. The SPA hydrates its auth store from this so the
             *     user menu shows the right handle after a hard refresh.
             */
            username: string;
            /** @description `CARGO_PKG_VERSION` of the running service. */
            version: string;
        };
        /** @description Inclusive time window bounds echoed back to the caller. */
        WindowBounds: {
            /**
             * Format: date-time
             * @description Start of the window (inclusive).
             */
            from: string;
            /**
             * Format: date-time
             * @description End of the window (inclusive).
             */
            to: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all registered agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"][];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_alerts: {
        parameters: {
            query?: {
                /** @description Include active alerts. */
                active?: boolean | null;
                /** @description Include silenced alerts. */
                silenced?: boolean | null;
                /** @description Include inhibited alerts. */
                inhibited?: boolean | null;
                /** @description Include unprocessed alerts. */
                unprocessed?: boolean | null;
                /**
                 * @description Single PromQL-style label matcher expression, e.g.
                 *     `alertname="HighLatency"`. Multiple matchers must be combined into
                 *     one expression by the caller (Alertmanager accepts comma-separated
                 *     matchers inside a single `filter` value).
                 */
                filter?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active alerts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSummary"][];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Alertmanager not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_alert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Alert fingerprint (hex) */
                fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSummary"];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Alert not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Alertmanager not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many attempts from this IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    query_instant: {
        parameters: {
            query: {
                /** @description PromQL expression (must reference a meshmon_ metric) */
                query: string;
                /** @description Evaluation timestamp */
                time?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instant query result (VM JSON pass-through) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Query rejected by whitelist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VictoriaMetrics not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    query_range: {
        parameters: {
            query: {
                /** @description PromQL expression (must reference a meshmon_ metric) */
                query: string;
                /** @description Start timestamp */
                start: string;
                /** @description End timestamp */
                end: string;
                /** @description Query resolution step */
                step: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Range query result (VM JSON pass-through) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Query rejected by whitelist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VictoriaMetrics not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    path_overview: {
        parameters: {
            query?: {
                /** @description Start of the time window (inclusive). Defaults to `to - 24h`. */
                from?: string | null;
                /** @description End of the time window (inclusive). Defaults to now. */
                to?: string | null;
                /**
                 * @description Optional protocol override (`icmp`, `udp`, or `tcp`). Returns 400 on
                 *     any other value.
                 */
                protocol?: string | null;
            };
            header?: never;
            path: {
                /** @description Source agent id */
                src: string;
                /** @description Target agent id */
                tgt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated path detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathOverviewResponse"];
                };
            };
            /** @description Invalid protocol override */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Source or target agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_routes: {
        parameters: {
            query?: {
                /** @description Start of the time window (inclusive). Defaults to 24 h ago. */
                from?: string | null;
                /** @description End of the time window (inclusive). Defaults to now. */
                to?: string | null;
                /** @description Maximum rows to return (1..=500, default 100). */
                limit?: number | null;
                /** @description Offset for pagination (>= 0, default 0). */
                offset?: number | null;
                /** @description Protocol filter: icmp, tcp, or udp. */
                protocol?: string;
            };
            header?: never;
            path: {
                /** @description Source agent id */
                src: string;
                /** @description Target agent id */
                tgt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated route snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutesPage"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_route_latest: {
        parameters: {
            query?: {
                /** @description Protocol filter: icmp, tcp, or udp. */
                protocol?: string;
            };
            header?: never;
            path: {
                /** @description Source agent id */
                src: string;
                /** @description Target agent id */
                tgt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest route snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSnapshotDetail"];
                };
            };
            /** @description Invalid protocol */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No snapshot found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_route_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source agent id */
                src: string;
                /** @description Target agent id */
                tgt: string;
                /** @description Snapshot database id */
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route snapshot detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSnapshotDetail"];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_recent_routes: {
        parameters: {
            query?: {
                /** @description Maximum rows to return (1..=100, default 10). */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent route snapshots across all pairs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSnapshotSummary"][];
                };
            };
            /** @description Invalid limit */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    web_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frontend runtime config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebConfigResponse"];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
