/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST `/api/auth/login` — authenticate and issue a session cookie.
         * @description - 200 + `LoginResponse` on success
         *     - 401 on wrong credentials (JSON body: `{"error": "invalid credentials"}`)
         *     - 500 only on infra failure (session store I/O, verify-task panic)
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST `/api/auth/logout` — invalidate the current session.
         * @description Idempotent: 200 whether or not the caller was logged in. The cookie is
         *     cleared either way.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/web-config` — return the frontend runtime config.
         * @description This handler is registered behind the `login_required!` layer, so
         *     unauthenticated requests never reach it — they are short-circuited by
         *     the middleware with a plain 401. The 401 response is documented here so
         *     the generated OpenAPI schema tells SPA clients exactly what to expect.
         */
        get: operations["web_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description POST body for `/api/auth/login`. */
        LoginRequest: {
            /**
             * @description Plaintext password. Verified against the PHC hash via argon2 inside
             *     `spawn_blocking`.
             */
            password: string;
            /** @description Username from the configured `[auth.users]` list. */
            username: string;
        };
        /** @description JSON response body for `/api/auth/login`. */
        LoginResponse: {
            /** @description Echoed username on success. */
            username: string;
        };
        /**
         * @description Runtime config the frontend needs before it can render dashboards.
         *
         *     Returned from `GET /api/web-config`; doubles as the SPA's session probe
         *     (401 when the caller has no valid session cookie).
         */
        WebConfigResponse: {
            /**
             * @description Base URL for embedding Grafana panels (e.g., `https://grafana.example/`).
             *     `None` if Grafana is not configured — omitted from the JSON body.
             */
            grafana_base_url?: string | null;
            /**
             * @description Map of logical dashboard name → Grafana dashboard UID. Empty
             *     when Grafana integration is not configured.
             */
            grafana_dashboards: {
                [key: string]: string;
            };
            /** @description `CARGO_PKG_VERSION` of the running service. */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many attempts from this IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    web_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frontend runtime config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebConfigResponse"];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
